Config = {}

Config.colors = {
    {name = "Black", price = 10, category = "color", index = 0},{name = "Carbon Black", price = 10, category = "color", index = 147},
    {name = "Hraphite", price = 10, category = "color", index = 1},{name = "Anhracite Black", price = 10, category = "color", index = 11},
    {name = "Black Steel", price = 10, category = "color", index = 2},{name = "Dark Steel", price = 10, category = "color", index = 3},
    {name = "Silver", price = 10, category = "color", index = 4},{name = "Bluish Silver", price = 10, category = "color", index = 5},
    {name = "Rolled Steel", price = 10, category = "color", index = 6},{name = "Shadow Silver", price = 10, category = "color", index = 7},
    {name = "Stone Silver", price = 10, category = "color", index = 8},{name = "Midnight Silver", price = 10, category = "color", index = 9},
    {name = "Cast Iron Silver", price = 10, category = "color", index = 10},{name = "Red", price = 10, category = "color", index = 27},
    {name = "Torino Red", price = 10, category = "color", index = 28},{name = "Formula Red", price = 10, category = "color", index = 29},
    {name = "Lava Red", price = 10, category = "color", index = 150},{name = "Blaze Red", price = 10, category = "color", index = 30},
    {name = "Grace Red", price = 10, category = "color", index = 31},{name = "Garnet Red", price = 10, category = "color", index = 32},
    {name = "Sunset Red", price = 10, category = "color", index = 33},{name = "Cabernet Red", price = 10, category = "color", index = 34},
    {name = "Wine Red", price = 10, category = "color", index = 143},{name = "Candy Red", price = 10, category = "color", index = 35},
    {name = "Hot Pink", price = 10, category = "color", index = 135},{name = "Pfsiter Pink", price = 10, category = "color", index = 137},
    {name = "Salmon Pink", price = 10, category = "color", index = 136},{name = "Sunrise Orange", price = 10, category = "color", index = 36},
    {name = "Orange", price = 10, category = "color", index = 38},{name = "Bright Orange", price = 10, category = "color", index = 138},
    {name = "Gold", price = 10, category = "color", index = 99},{name = "Bronze", price = 10, category = "color", index = 90},
    {name = "Yellow", price = 10, category = "color", index = 88},{name = "Race Yellow", price = 10, category = "color", index = 89},
    {name = "Dew Yellow", price = 10, category = "color", index = 91},{name = "Dark Green", price = 10, category = "color", index = 49},
    {name = "Racing Green", price = 10, category = "color", index = 50},{name = "Sea Green", price = 10, category = "color", index = 51},
    {name = "Olive Green", price = 10, category = "color", index = 52},{name = "Bright Green", price = 10, category = "color", index = 53},
    {name = "Gasoline Green", price = 10, category = "color", index = 54},{name = "Lime Green", price = 10, category = "color", index = 92},
    {name = "Midnight Blue", price = 10, category = "color", index = 141},
    {name = "Galaxy Blue", price = 10, category = "color", index = 61},{name = "Dark Blue", price = 10, category = "color", index = 62},
    {name = "Saxon Blue", price = 10, category = "color", index = 63},{name = "Blue", price = 10, category = "color", index = 64},
    {name = "Mariner Blue", price = 10, category = "color", index = 65},{name = "Harbor Blue", price = 10, category = "color", index = 66},
    {name = "Diamond Blue", price = 10, category = "color", index = 67},{name = "Surf Blue", price = 10, category = "color", index = 68},
    {name = "Nautical Blue", price = 10, category = "color", index = 69},{name = "Racing Blue", price = 10, category = "color", index = 73},
    {name = "Ultra Blue", price = 10, category = "color", index = 70},{name = "Light Blue", price = 10, category = "color", index = 74},
    {name = "Chocolate Brown", price = 10, category = "color", index = 96},{name = "Bison Brown", price = 10, category = "color", index = 101},
    {name = "Creeen Brown", price = 10, category = "color", index = 95},{name = "Feltzer Brown", price = 10, category = "color", index = 94},
    {name = "Maple Brown", price = 10, category = "color", index = 97},{name = "Beechwood Brown", price = 10, category = "color", index = 103},
    {name = "Sienna Brown", price = 10, category = "color", index = 104},{name = "Saddle Brown", price = 10, category = "color", index = 98},
    {name = "Moss Brown", price = 10, category = "color", index = 100},{name = "Woodbeech Brown", price = 10, category = "color", index = 102},
    {name = "Straw Brown", price = 10, category = "color", index = 99},{name = "Sandy Brown", price = 10, category = "color", index = 105},
    {name = "Bleached Brown", price = 10, category = "color", index = 106},{name = "Schafter Purple", price = 10, category = "color", index = 71},
    {name = "Spinnaker Purple", price = 10, category = "color", index = 72},{name = "Midnight Purple", price = 10, category = "color", index = 142},
    {name = "Bright Purple", price = 10, category = "color", index = 145},{name = "Cream", price = 10, category = "color", index = 107},
    {name = "Ice White", price = 10, category = "color", index = 111},{name = "Frost White", price = 10, category = "color", index = 112}}

    Config.metalcolors = {
    {name = "Brushed Steel", price = 10, category = "color", index = 117},
    {name = "Brushed Black Steel",price = 10, category = "color", index = 118},
    {name = "Brushed Aluminum",price = 10, category = "color", index = 119},
    {name = "Pure Gold",price = 10, category = "color", index = 158},
    {name = "Brushed Gold",price = 10, category = "color", index = 159}
    }
    
    Config.mattecolors = {
    {name = "Black", price = 10, category = "color", index = 12},
    {name = "Gray", price = 10, category = "color", index = 13},
    {name = "Light Gray", price = 10, category = "color", index = 14},
    {name = "Ice White", price = 10, category = "color", index = 131},
    {name = "Blue", price = 10, category = "color", index = 83},
    {name = "Dark Blue", price = 10, category = "color", index = 82},
    {name = "Midnight Blue", price = 10, category = "color", index = 84},
    {name = "Midnight Purple", price = 10, category = "color", index = 149},
    {name = "Schafter Purple", price = 10, category = "color", index = 148},
    {name = "Red", price = 10, category = "color", index = 39},
    {name = "Dark Red", price = 10, category = "color", index = 40},
    {name = "Orange", price = 10, category = "color", index = 41},
    {name = "Yellow", price = 10, category = "color", index = 42},
    {name = "Lime Green", price = 10, category = "color", index = 55},
    {name = "Green", price = 10, category = "color", index = 128},
    {name = "Frost Green", price = 10, category = "color", index = 151},
    {name = "Foliage Green", price = 10, category = "color", index = 155},
    {name = "Olive Darb", price = 10, category = "color", index = 152},
    {name = "Dark Earth", price = 10, category = "color", index = 153},
    {name = "Desert Tan", price = 10, category = "color", index = 154}
    }